export const ACTIONS = [
  {
    id: 'a',
    marker: 'A',
    icon: 'Greet',
    label: 'Greeting',
    animation: 'wave',
    pose: 'left-far',
    dialogues: ['Hello there.', 'Ready when you are.', 'Target acquired.'],
  },
  {
    id: 'b',
    marker: 'B',
    icon: 'Focus',
    label: 'Focus',
    animation: 'focus',
    pose: 'left-near',
    dialogues: ['Locking in.', 'Signal steady.', 'Holding attention.'],
  },
  {
    id: 'c',
    marker: 'C',
    icon: 'Approve',
    label: 'Approve',
    animation: 'approve',
    pose: 'right-near',
    dialogues: ['Confirmed.', 'Looks good.', 'Approved.'],
  },
  {
    id: 'd',
    marker: 'D',
    icon: 'Bright',
    label: 'Celebrate',
    animation: 'celebrate',
    pose: 'right-far',
    dialogues: ['Nice choice.', 'That one shines.', 'Showing off a little.'],
  },
];
