export const GAME_STATES = {
  ASSET_READY: 'ASSET_READY',
  INTRO: 'INTRO',
  GREETING: 'GREETING',
  HOLD_TO_UNLOCK: 'HOLD_TO_UNLOCK',
  UNLOCK_SUCCESS: 'UNLOCK_SUCCESS',
  GUIDED_ACTION_REVEAL: 'GUIDED_ACTION_REVEAL',
  FREE_ACTION_SELECTION: 'FREE_ACTION_SELECTION',
  ACTION_PLAYING: 'ACTION_PLAYING',
};
